# Complete list of all available properties: https://docs.upsun.com/create-apps/app-reference.html
applications:
  saleor:
    # Application source code directory
    source:
      root: "/"

    # The runtime the application uses.
    # Complete list of available runtimes: https://docs.upsun.com/create-apps/app-reference.html#types
    stack: ["python@3.9", "nodejs@20"]

    # How many resources to devote to the app. Defaults to AUTO in production environments.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#sizes
    # size:

    # The relationships of the application with services or other applications.
    # The left-hand side is the name of the relationship as it will be exposed
    # to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
    # side is in the form `<service name>:<endpoint name>`.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#relationships
    relationships:
      postgresql: "postgresql:postgresql"
      redis: "redis:redis"
      

    # Mounts define directories that are writable after the build is complete.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#mounts
    mounts:
       "/.cache": # Represents the path in the app.
         source: "storage" # "local" sources are unique to the app, while "service" sources can be shared among apps.
         source_path: "cache" # The subdirectory within the mounted disk (the source) where the mount should point.
       "media": # Represents the path in the app.
         source: "storage" # "local" sources are unique to the app, while "service" sources can be shared among apps.
         source_path: "media" # The subdirectory within the mounted disk (the source) where the mount should point.

    # The web key configures the web server running in front of your app.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#web
    web:
      # Commands are run once after deployment to start the application process.
      # More information: https://docs.upsun.com/create-apps/app-reference.html#web-commands
      commands:
        # The command to launch your app. If it terminates, it’s restarted immediately.
        # You can use the $PORT or the $SOCKET environment variable depending on the socket family of your upstream
        start: "poetry run gunicorn  -b unix:$SOCKET app.wsgi --log-file -"
      # You can listen to a UNIX socket (unix) or a TCP port (tcp, default).
      # Whether your app should speak to the webserver via TCP or Unix socket. Defaults to tcp
      # More information: https://docs.upsun.com/create-apps/app-reference.html#where-to-listen
      upstream:
        # Whether your app should speak to the webserver via TCP or Unix socket. Defaults to tcp
        # More information: https://docs.upsun.com/create-apps/app-reference.html#where-to-listen
        socket_family: unix
      # Each key in locations is a path on your site with a leading /.
      # More information: https://docs.upsun.com/create-apps/app-reference.html#locations
      locations:
        "/":
          passthru: true
          
        "/static":
          allow: true
          expires: "1h"
          root: "static"
          
        

    # Alternate copies of the application to run as background processes.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#workers
    workers:
      celery:
        commands:
          start: "celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B"

    # The timezone for crons to run. Format: a TZ database name. Defaults to UTC, which is the timezone used for all logs
    # no matter the value here. More information: https://docs.upsun.com/create-apps/timezone.html
    # timezone: <time-zone>

    # Access control for roles accessing app environments.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#access
    # access:

    # Variables to control the environment. More information: https://docs.upsun.com/create-apps/app-reference.html#variables
    variables:
      env:
        N_PREFIX: "/app/.global"
        POETRY_VERSION: "1.4.0"
        POETRY_VIRTUALENVS_IN_PROJECT: "true"
        

    # Outbound firewall rules for the application. More information: https://docs.upsun.com/create-apps/app-reference.html#firewall
    # firewall:

    # Hooks allow you to customize your code/environment as the project moves through the build and deploy stages
    # More information: https://docs.upsun.com/create-apps/app-reference.html#hooks
    hooks:
      # The build hook is run after any build flavor.
      # More information: https://docs.upsun.com/create-apps/hooks/hooks-comparison.html#build-hook
      build: |
        set -eux
        # Set PIP_USER to 0 so that Poetry does not complain
        export PIP_USER=0
        # Install poetry as a global tool
        pip install poetry==$POETRY_VERSION
        poetry config virtualenvs.create false
        poetry install  --no-root
        npm i
        # Collect static files so that they can be served by Upsun
        poetry run python manage.py collectstatic --noinput
        
      # The deploy hook is run after the app container has been started, but before it has started accepting requests.
      # More information: https://docs.upsun.com/create-apps/hooks/hooks-comparison.html#deploy-hook
      deploy: |
        set -eux
        poetry run python manage.py migrate
        

      # The post_deploy hook is run after the app container has been started and after it has started accepting requests.
      # More information: https://docs.upsun.com/create-apps/hooks/hooks-comparison.html#deploy-hook
      # post_deploy: |

    # Scheduled tasks for the app.
    # More information: https://docs.upsun.com/create-apps/app-reference.html#crons
    # crons:

    # Customizations to your PHP or Lisp runtime. More information: https://docs.upsun.com/create-apps/app-reference.html#runtime
    # runtime:

    # More information: https://docs.upsun.com/create-apps/app-reference.html#additional-hosts
    # additional_hosts:

# The services of the project.
#
# Each service listed will be deployed
# to power your Upsun project.
# More information: https://docs.upsun.com/add-services.html
# Full list of available services: https://docs.upsun.com/add-services.html#available-services
services:
  postgresql:
    type: postgresql:15 # All available versions are: 15, 14, 13, 12, 11

  redis:
    type: redis:7.0 # All available versions are: 7.0, 6.2

  

# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Upsun.
# More information: https://docs.upsun.com/define-routes.html
routes:
  "https://{default}/":
    type: upstream
    upstream: "saleor:http"
  # A basic redirect definition
  # More information: https://docs.upsun.com/define-routes.html#basic-redirect-definition
  "https://www.{default}":
    type: redirect
    to: "https://{default}/"
